version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "8765:8765"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d 
    environment:
      POSTGRES_DB: receipt_extraction
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54320:5432"
